---
title: "R Notebook"
output: html_notebook
---




```{r}
rm(list = ls())

library(tidyverse)
library(riskRegression)
library(plyr)
#library(tidysurv)
library(data.table)
library(stringr)
library(parallel)
library(tableone)
library(muhaz)
library(survival)
library(Hmisc)
library(MASS)
library(mfp)
library(reshape2)
library(flexsurv)
library(devtools)
library(prodlim)
library(rms)
library(rstpm2)
library(survcomp)
library(glmnet)
library(caret)
library(sjPlot)
library(knitr)
library(webshot)
library(pROC)
library(rmda)
library(pseudo)
library(lava)
library(pec)
library(mice)
library(miceadds)
library(dcurves)

```


# IMPUTED DATA

## 1. Benchmark model

```{r}

imputed_data_with_scores = readstata13::read.dta13("IMPUTED_data_with__Benchmark_scores.dta")

imputed_data_with_scores = imputed_data_with_scores %>% dplyr::select(
  patient_id,
  time1,status1,
  LP,
 score_2yrs_Benchmark,
 score_5yrs_Benchmark) %>% dplyr::rename(PRACTICE_PATIENT_ID=patient_id)



```



## 1. Decision curve - stdca

### Import stdca function from https://github.com/survival-lumc/ValidationCompRisks/tree/main/R

```{r}
source(here::here("stdca.R"))

```

```{r}
options(bitmapType='cairo')
```

### 2 years

#### Benchmark

```{r}

# 1) Run stdca across all thresholds up to 1
dca_vdata <- stdca(
  data      = clinical_utility_data,
  outcome   = "status1",
  ttoutcome = "time1",
  timepoint = 2,
  predictors = "score_2yrs_Benchmark",
  xstop     = 0.5,      # evaluate thresholds up to 1.0
  ymin      = -0.01,
  graph     = FALSE,
  cmprsk    = TRUE
)

# 2) Save plot
png(
  filename = "decision_curve_Benchmark_2yrs_stdca.png",
  width  = 2000,
  height = 1600,
  res    = 300
)

oldpar <- par(
  xaxs = "i",
  yaxs = "i",
  las  = 1,
  mar  = c(6.1, 5.8, 4.1, 2.1),
  mgp  = c(4.25, 1, 0)
)

nb <- dca_vdata$net.benefit

# Y-limits: use the observed range (robust) so the full curve is visible
yl <- c(-0.005, 0.005)

plot(
  nb$threshold,
  nb$score_2yrs_Benchmark,
  type = "l",
  lwd  = 2,
  lty  = 1,
  xlab = "",
  ylab = "Net Benefit",
  xlim = c(0, 0.5),
  ylim = yl,
  bty  = "n",
  xaxt = "n"
)

lines(nb$threshold, nb$none, type = "l", lwd = 2, lty = 4, col = "black")
lines(nb$threshold, nb$all,  type = "l", lwd = 2, col = "darkgray")

legend(
  "topright",
  c("Treat all", "Treat none", "Prediction model"),
  lwd = c(2, 2, 2),
  lty = c(1, 4, 1),
  col = c("darkgray", "black", "black"),
  bty = "n"
)

# Primary x-axis: 0 to 1
axis(1, at = seq(0, 1, by = 0.1))

# Secondary x-axis: harm:benefit ratio (p_t : 1-p_t) for 0.1 to 0.9
axis(
  1,
  pos = par("usr")[3] - 0.12 * diff(par("usr")[3:4]),  # place below plot area
  at = c(0.1, 0.2, 0.3, 0.4, 0.5),
  labels = c("1:9", "1:4", "3:7", "2:3", "1:1")
)

mtext("Threshold probability", 1, line = 2)
mtext("Harm to benefit ratio", 1, line = 5)
title("Validation data (2 years)")

par(oldpar)
dev.off()

```




### 5 years

#### Benchmark

```{r}

# 1) Run stdca across all thresholds up to 1
dca_vdata <- stdca(
  data      = clinical_utility_data,
  outcome   = "status1",
  ttoutcome = "time1",
  timepoint = 5,
  predictors = "score_5yrs_Benchmark",
  xstop     = 0.5,      # evaluate thresholds up to 1.0
  ymin      = -0.01,
  graph     = FALSE,
  cmprsk    = TRUE
)

# 2) Save plot
png(
  filename = "decision_curve_Benchmark_5yrs_stdca.png",
  width  = 2000,
  height = 1600,
  res    = 300
)

oldpar <- par(
  xaxs = "i",
  yaxs = "i",
  las  = 1,
  mar  = c(6.1, 5.8, 4.1, 2.1),
  mgp  = c(4.25, 1, 0)
)

nb <- dca_vdata$net.benefit

write.csv(nb,"NetBenefit5years.csv")

# Y-limits: use the observed range (robust) so the full curve is visible
yl <- c(-0.005, 0.005)
plot(
  nb$threshold,
  nb$score_5yrs_Benchmark,
  type = "l",
  lwd  = 2,
  lty  = 1,
  xlab = "",
  ylab = "Net Benefit",
  xlim = c(0, 0.5),
  ylim = yl,
  bty  = "n",
  xaxt = "n"
)

lines(nb$threshold, nb$none, type = "l", lwd = 2, lty = 4, col = "black")
lines(nb$threshold, nb$all,  type = "l", lwd = 2, col = "darkgray")

legend(
  "topright",
  c("Treat all", "Treat none", "Prediction model"),
  lwd = c(2, 2, 2),
  lty = c(1, 4, 1),
  col = c("darkgray", "black", "black"),
  bty = "n"
)

# Primary x-axis: 0 to 1
axis(1, at = seq(0, 1, by = 0.1))

# Secondary x-axis: harm:benefit ratio (p_t : 1-p_t) for 0.1 to 0.9
axis(
  1,
  pos = par("usr")[3] - 0.12 * diff(par("usr")[3:4]),  # place below plot area
  at = c(0.1, 0.2, 0.3, 0.4, 0.5),
  labels = c("1:9", "1:4", "3:7", "2:3", "1:1")
)

mtext("Threshold probability", 1, line = 2)
mtext("Harm to benefit ratio", 1, line = 5)
title("5 years")

par(oldpar)
dev.off()

```

